apiVersion: v1
kind: BuildConfig
metadata:
  name: fis-rest-1-pipeline
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/rahmed-rh/safaricom-fis-1.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers: []
status:
  lastVersion: 0
